import { beforeEach, describe, expect, it } from 'vitest'
import { createApp } from '../src/index'
import { selectAIContext } from '../src/application/ai-service'
import { Phase4Service } from '../src/application/phase4-service'
import { StravaActivityConnector } from '../src/application/strava-connector'
import { MemoryRunStore } from './memory-store'

let store:MemoryRunStore
let app:ReturnType<typeof createApp>
async function register(email:string){const r=await app.request('http://localhost/api/auth/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,displayName:'Pelari',password:'correct-horse-battery-staple'})});return r.headers.get('set-cookie')!.split(';')[0]}
async function req(path:string,cookie?:string,method='GET',body?:unknown){const r=await app.request(`http://localhost${path}`,{method,headers:{...(cookie?{Cookie:cookie}:{}),...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined});return{status:r.status,body:await r.json() as any}}
const profile=(name='Budi')=>({displayName:name,runningArea:'Purwokerto',preferredDays:['Jumat','Minggu'],preferredTime:'pagi',preferredDistances:['5K','10K'],primaryGoal:'Konsisten',preferredEventTypes:['road'],runningWithOthersPreference:'lebih_suka_bareng',communities:['Banyumas Runners'],notes:null,onboardingCompletedAt:'2026-09-17T00:00:00.000Z'})
const recurrence=(name='MJW')=>({name,activityType:'community_run',recurrenceRule:'FREQ=WEEKLY;BYDAY=FR',usualDay:'Jumat',usualTime:'malam',usualLocation:null,community:null,expectedDistanceMeters:null,notes:'Mlayu Jumat Wengi; kehadiran tidak diasumsikan.',source:'user_confirmed',relevanceWeight:.85,active:true})
const event=(eventDate:null|string=null)=>({name:'Skybridge Race Run',aliases:['Sky Bridge Run','Skybridge Run','KAI Daop 5 Skybridge Run'],editionYear:2026,monthHint:'November',eventDate,location:'Purwokerto',organizer:null,distanceOrCategory:null,registrationUrl:null,registrationDeadline:null,sourceUrl:null,status:'candidate',dateStatus:'unverified',participationIntent:'interested',notes:'Tanggal belum terverifikasi.'})

beforeEach(()=>{store=new MemoryRunStore();app=createApp(()=>store)})

describe('Phase 4 personal runner API',()=>{
  it('requires authentication for all personal resources',async()=>{for(const path of ['/api/profile','/api/home','/api/activities','/api/recurring-activities','/api/events','/api/integrations/strava'])expect((await req(path)).status).toBe(401)})
  it('creates and updates an owner-scoped profile with optional values',async()=>{const a=await register('a4@example.com'),b=await register('b4@example.com');expect((await req('/api/profile',a,'PUT',profile())).status).toBe(200);expect((await req('/api/profile',a)).body.data.displayName).toBe('Budi');expect((await req('/api/profile',b)).body.data).toBeNull();await req('/api/profile',a,'PUT',{...profile('Ayu'),runningArea:null});expect((await req('/api/profile',a)).body.data).toMatchObject({displayName:'Ayu',runningArea:null})})
  it('validates profile input',async()=>{const c=await register('invalid4@example.com');const r=await req('/api/profile',c,'PUT',{...profile(),displayName:''});expect(r.status).toBe(400);expect(r.body.error.code).toBe('VALIDATION_ERROR')})
  it('keeps configurable MJW recurrence separate from factual occurrence status',async()=>{const a=await register('mjw@example.com'),b=await register('other@example.com');const created=(await req('/api/recurring-activities',a,'POST',recurrence())).body.data;expect(created).toMatchObject({name:'MJW',recurrenceRule:'FREQ=WEEKLY;BYDAY=FR',relevanceWeight:.85});const cross=await req(`/api/recurring-activities/${created.id}/occurrences`,b,'PUT',{scheduledAt:'2026-09-18T12:00:00.000Z',status:'attended',linkedRunningActivityId:null,notes:null});expect(cross.status).toBe(404);for(const status of ['planned','attended','skipped','unknown']){const r=await req(`/api/recurring-activities/${created.id}/occurrences`,a,'PUT',{scheduledAt:`2026-09-${status==='planned'?'18':status==='attended'?'25':status==='skipped'?'26':'27'}T12:00:00.000Z`,status,linkedRunningActivityId:null,notes:null});expect(r.status).toBe(200)}expect((await req('/api/recurring-activities/occurrences',a)).body.data).toHaveLength(4)})
  it('stores running activities with missing metrics and deduplicates provider external IDs',async()=>{const c=await register('activity4@example.com');const input={startedAt:'2026-09-17T01:00:00.000Z',endedAt:null,durationSeconds:null,distanceMeters:null,paceSecondsPerKm:null,elevationMeters:null,effort:null,feeling:null,source:'strava',externalId:'strava-42',eventId:null,recurringActivityId:null,notes:null};const first=(await req('/api/activities',c,'POST',input)).body.data;const second=(await req('/api/activities',c,'POST',input)).body.data;expect(first.id).toBe(second.id);expect((await req('/api/activities',c)).body.data).toHaveLength(1);expect(first.paceSecondsPerKm).toBeNull()})
  it('preserves Skybridge uncertainty and evidence without predicting attendance',async()=>{const c=await register('event4@example.com');const invalid=await req('/api/events',c,'POST',event('2026-11-10T00:00:00.000Z'));expect(invalid.status).toBe(400);const created=(await req('/api/events',c,'POST',event())).body.data;for(const evidence of [{evidenceType:'prior_participation',evidenceStrength:'strong'},{evidenceType:'repost',evidenceStrength:'moderate'}])await req(`/api/events/${created.id}/evidence`,c,'POST',{...evidence,sourceUrl:null,observedAt:'2026-09-17T00:00:00.000Z',notes:null});const context=(await req(`/api/events/${created.id}/context`,c)).body.data;expect(context.event).toMatchObject({name:'Skybridge Race Run',eventDate:null,dateStatus:'unverified'});expect(context.relevance).toBe('high');expect(context.attendancePredicted).toBe(false);expect(JSON.stringify(context)).not.toContain('KAI Commuter Run')})
  it('keeps Strava disconnected and honest without credentials or browser tokens',async()=>{const c=await register('strava4@example.com');const status=await req('/api/integrations/strava',c);expect(status.body.data).toMatchObject({status:'disconnected',available:false});expect(JSON.stringify(status.body)).not.toMatch(/access_token|refresh_token|client_secret/);const connect=await req('/api/integrations/strava/connect',c,'POST');expect(connect.status).toBe(503);expect(connect.body.error.code).toBe('PROVIDER_UNAVAILABLE')})
  it('protects Tanya AI and reports unavailable Groq truthfully',async()=>{expect((await req('/api/ai/ask',undefined,'POST',{question:'Besok aku lari apa?'})).status).toBe(401);const c=await register('ai4@example.com');const r=await req('/api/ai/ask',c,'POST',{question:'Besok aku lari apa?'});expect(r.status).toBe(503);expect(r.body.error.code).toBe('AI_PROVIDER_UNAVAILABLE');expect(JSON.stringify(r.body)).not.toContain('GROQ_API_KEY')})
  it('minimizes AI context by question intent and owner',async()=>{const a=await register('ctx-a@example.com'),b=await register('ctx-b@example.com');await req('/api/profile',a,'PUT',profile('Owner A'));await req('/api/profile',b,'PUT',profile('Owner B'));await req('/api/recurring-activities',a,'POST',recurrence());const aId=[...store.users.values()].find(x=>x.email==='ctx-a@example.com')!.id;const context=await selectAIContext(store,aId,'Besok ada MJW?');expect(context.items.find(x=>x.kind==='profile')?.data.displayName).toBe('Owner A');expect(context.items.filter(x=>x.kind==='recurring_activity')).toHaveLength(1);expect(context.items.filter(x=>x.kind==='running_activity')).toHaveLength(0);expect(context.items.filter(x=>x.kind==='event')).toHaveLength(0);expect(JSON.stringify(context)).not.toContain('Owner B')})
  it('rejects cross-owner links from activities and occurrences',async()=>{const a=await register('links-a@example.com'),b=await register('links-b@example.com');const eventId=(await req('/api/events',a,'POST',event())).body.data.id;const recurringId=(await req('/api/recurring-activities',a,'POST',recurrence('Latihan A'))).body.data.id;const input={startedAt:'2026-09-17T01:00:00.000Z',endedAt:null,durationSeconds:null,distanceMeters:null,paceSecondsPerKm:null,elevationMeters:null,effort:null,feeling:null,source:'manual',externalId:null,eventId,recurringActivityId:null,notes:null};expect((await req('/api/activities',b,'POST',input)).status).toBe(404);const bActivity=(await req('/api/activities',b,'POST',{...input,eventId:null})).body.data;expect((await req(`/api/recurring-activities/${recurringId}/occurrences`,a,'PUT',{scheduledAt:'2026-09-30T12:00:00.000Z',status:'attended',linkedRunningActivityId:bActivity.id,notes:null})).status).toBe(404)})
  it('normalizes and idempotently imports completed Strava runs',async()=>{await register('connector@example.com');const ownerId=[...store.users.values()].find(x=>x.email==='connector@example.com')!.id;const connector=new StravaActivityConnector(new Phase4Service(store));const payload={id:991,sport_type:'Run',start_date:'2026-09-17T05:00:00Z',moving_time:1800,distance:5000,total_elevation_gain:35,name:'Morning Run'};const first=await connector.importCompletedActivity(ownerId,payload);const second=await connector.importCompletedActivity(ownerId,payload);expect(first.id).toBe(second.id);expect(first).toMatchObject({source:'strava',externalId:'991',durationSeconds:1800,distanceMeters:5000,paceSecondsPerKm:360,elevationMeters:35});expect(first.endedAt).toBe('2026-09-17T05:30:00.000Z');expect(store.activities).toHaveLength(1);expect(()=>connector.normalizeActivity({...payload,sport_type:'Ride'})).toThrowError(/bukan aktivitas lari/)})
  it('surfaces event relevance without changing participation intent',async()=>{const c=await register('home4@example.com');await req('/api/profile',c,'PUT',profile());const normal=(await req('/api/events',c,'POST',{...event(),name:'Event Lokal',aliases:[]})).body.data;const high=(await req('/api/events',c,'POST',event())).body.data;await req(`/api/events/${high.id}/evidence`,c,'POST',{evidenceType:'prior_participation',evidenceStrength:'strong',sourceUrl:null,observedAt:'2026-09-17T00:00:00.000Z',notes:null});await req(`/api/events/${high.id}/evidence`,c,'POST',{evidenceType:'repost',evidenceStrength:'moderate',sourceUrl:null,observedAt:'2026-09-17T00:00:00.000Z',notes:null});const home=(await req('/api/home',c)).body.data;expect(home.eventContexts[0]).toMatchObject({event:{id:high.id,participationIntent:'interested'},relevance:'high',attendancePredicted:false});expect(home.eventContexts.find((x:any)=>x.event.id===normal.id).attendancePredicted).toBe(false)})
  it('requires a verified event date and keeps Skybridge distinct from KAI Commuter Run',async()=>{const c=await register('identity4@example.com');expect((await req('/api/events',c,'POST',{...event(),name:'Event Terverifikasi',aliases:[],dateStatus:'verified'})).status).toBe(400);const mixed={...event(),aliases:['KAI Commuter Run Jakarta']};const result=await req('/api/events',c,'POST',mixed);expect(result.status).toBe(400);expect(result.body.error.code).toBe('VALIDATION_ERROR')})
})
